### ISSUE TITLE
Emoticon download

### ISSUE THREAD

**Issue by voidpirate** [netromdk/slacker#1]
API endpoint: https://api.slack.com/methods/emoji.list

Command: `slacker downloademoticons <local_save_path>`

The command should download all custom emoji from a workspace. The `local_save_path` is a simple JSON format that describes where the emoji are saved on disk and if any emoji aliases were saved.

The JSON format for the save file will be something like this:

```json
{
  "emojis": {
    "metal": "/local_save_path/46ec6f2bb0.png",
    "shipit": "alias:metal"
  }
}
```

**Comment by netromdk** [comment]
Closed as part of #48.
