### ISSUE TITLE
Tab-complete commands

### ISSUE THREAD

**Issue by netromdk** [netromdk/slacker#18]
Tab-completion with no input should show something like:
```
> <tab>
X commands/aliases available.. Press tab again to list them all.
```

The commands should be shown similar to how the help command does it.

Tab-completion with some input should complete to the longest common string of all available commands/aliases, like: `> he<tab>` becomes `> help` or `> set<tab>` becomes `> setVersion` if, for instance, there are two commands "setVersionMajor" and "setVersionMinor". If tab-completing again, with several candidates available, show same message as the first message above and the second tab-completion expands to all of them.

Only tab complete if character right before <kbd>tab</kbd> isn't whitespace and neither if any whitespaces exist between input values, like `> help <tab>` and `> help with this<tab>`.

Maybe get some inspiration from how lldb does it.

**Comment by voidpirate** [comment]
This is handled #55
