### ISSUE TITLE
Create workspaces via command

### ISSUE THREAD

**Issue by netromdk** [netromdk/slacker#64]
I was thinking that now with the masked tokens input, shouldn't we make it possible to create workspaces via the `config` command, @voidpirate?

It could be via a `--create` argument that asks for info just like `--init` does it, and also checks auth of the token.

**Comment by netromdk** [comment]
And also to remove inactive workspaces with `--remove <workspace>`.

**Comment by voidpirate** [comment]
Yeah, I agree that we should allow workspace creation via REPL now that we have password input.

**Comment by netromdk** [comment]
Okay, I'll add that later today. 👍
