### ISSUE TITLE
Rename workspace to team

### ISSUE THREAD

**Issue by netromdk** [netromdk/slacker#70]
In the Slack API they mostly refer to what we call "workspaces" as "teams". Maybe we should rename it to teams to be 1-to-1?

**Comment by netromdk** [comment]
But I'm not sure because inside Slack they call it workspaces themselves.. So it's probably fine as it is.

**Comment by voidpirate** [comment]
Yeah that a bit confusing actually. I think just to keep our commands API 1-to-1 with Slack API we should rename it.

**Comment by netromdk** [comment]
The extra confusing part is that they call them workspaces when they talk about the token scope, like user, workspace, or bot. Haha..

**Comment by voidpirate** [comment]
I'm going to leave this as workspace. I'm hoping that Slack will clean up their API to reflect what the client exposes to client users. Since we already have "workspace" it will be more friendly to users of slacker, since the official Slack client uses workspaces.

Thoughts?

**Comment by netromdk** [comment]
Yeah, let's leave it as-is.
